let Imagenes = [
    {
        id : "Nelson",
        src : "/IMG/Nelson2.png",
        texto : "HOLA! <br> Soy Nelson <br> Soy diseñador de software."
    },

    {
        id : "Sebastian",
        src : "/IMG/Sebastian2.png",
        texto : "HOLA! <br> Soy Sebastian <br> Soy Líder del equipo, Scrum master."
    },

    {
        id : "Felipe",
        src : "/IMG/Felipe2.png",
        texto : "HOLA! <br> Soy Felipe <br> Soy Diseñador de software."
    },

    {
        id : "Manuela",
        src : "/IMG/Manuela2.png",
        texto : "HOLA! <br> Soy Manuela <br> Soy Diseñadora UI."
    },
    
    {
        id : "Maria",
        src : "/IMG/Nelson2.png",
        texto : "HOLA! <br> Soy Maria <br> Soy Administradora configuración."
    },

    {
        id : "Shaiel",
        src : "/IMG/Nelson2.png",
        texto : "HOLA! <br> Soy Shaiel <br> Soy Tester."
    }
]
