let Imagenes = [
    {
        id : "Nelson",
        src : "/IMG/Nelson2.png",
        texto : "HOLA! <br> Soy Nelson <br> Soy diseñador de software <br> Me gusta"
    },

    {
        id : "Sebastian",
        src : "/IMG/Sebastian2.png",
        texto : "HOLA! <br> Soy Sebastian <br> Soy Líder del equipo, Scrum master <br> Me gusta"
    },

    {
        id : "Felipe",
        src : "/IMG/Felipe2.png",
        texto : "HOLA! <br> Soy Felipe <br> Soy Diseñador de software <br> Me gusta"
    },

    {
        id : "Manuela",
        src : "/IMG/Manuela2.png",
        texto : "HOLA! <br> Soy Manuela <br> Soy Diseñadora UI <br> Me gusta dibujar y programar."
    },
    
    {
        id : "Maria",
        src : "/IMG/Nelson2.png",
        texto : "HOLA! <br> Soy Maria <br> Soy Administradora configuración <br> Me gusta"
    },

    {
        id : "Shaiel",
        src : "/IMG/Nelson2.png",
        texto : "HOLA! <br> Soy Shaiel <br> Soy Tester <br> Me gusta"
    }
]
